# Generated by Django 4.1.2 on 2022-11-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='nombre',
        ),
    ]
