# Generated by Django 4.1.2 on 2022-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRoom', '0002_rename_name_room_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='nombre',
            new_name='name',
        ),
    ]
