# Generated by Django 4.1.2 on 2022-11-16 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aceite',
            options={'ordering': ['nombre', 'varietal'], 'verbose_name': 'Mis Aceite'},
        ),
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['user', 'imagen'], 'verbose_name': 'Los Avatare'},
        ),
        migrations.AlterModelOptions(
            name='espumante',
            options={'ordering': ['nombre', 'varietal', 'añada'], 'verbose_name': 'Mis Espumante'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['nombre', 'apellido', 'cargo', 'email'], 'verbose_name': 'Los Miembro'},
        ),
        migrations.AlterModelOptions(
            name='vino',
            options={'ordering': ['nombre', 'varietal', 'añada'], 'verbose_name': 'Mis Vino'},
        ),
        migrations.AlterUniqueTogether(
            name='aceite',
            unique_together={('nombre', 'varietal')},
        ),
        migrations.AlterUniqueTogether(
            name='avatar',
            unique_together={('user', 'imagen')},
        ),
        migrations.AlterUniqueTogether(
            name='espumante',
            unique_together={('nombre', 'varietal', 'añada')},
        ),
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together={('nombre', 'apellido', 'cargo', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='vino',
            unique_together={('nombre', 'varietal', 'añada')},
        ),
    ]
